# Generated by Django 5.2.6 on 2025-09-05 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('artist', models.CharField(blank=True, max_length=120, null=True)),
                ('key', models.CharField(blank=True, max_length=10, null=True)),
                ('bpm', models.PositiveIntegerField(blank=True, null=True)),
                ('lyrics_excerpt', models.TextField(blank=True, null=True)),
                ('links', models.TextField(blank=True, null=True)),
                ('category', models.CharField(choices=[('exaltacao', 'Exaltação'), ('adoracao', 'Adoração'), ('neutra', 'Neutra')], default='neutra', max_length=20)),
                ('themes', models.CharField(blank=True, max_length=200, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
