# Generated by Django 5.2.6 on 2025-09-07 00:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicas', '0002_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Band',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('country', models.CharField(choices=[('br', 'Brasil'), ('us', 'Estados Unidos'), ('pt', 'Portugal'), ('fr', 'França'), ('de', 'Alemanha'), ('es', 'Espanha'), ('mx', 'México'), ('jp', 'Japão'), ('kr', 'Coreia do Sul')], max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='song',
            name='band',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='songs', to='musicas.band'),
        ),
    ]
