# Generated by Django 5.2.6 on 2025-09-07 03:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicas', '0004_userprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=2)),
            ],
        ),
        migrations.AddField(
            model_name='band',
            name='members',
            field=models.ManyToManyField(related_name='bands', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='band',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='musicas.company'),
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('module', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('feito', 'Feito'), ('pendente', 'Pendente'), ('em andamento', 'Em andamento')], max_length=20)),
                ('prazo', models.DateField(blank=True, null=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('equipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musicas.band')),
                ('responsavel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
