# Generated by Django 5.2.6 on 2025-09-07 03:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicas', '0005_company_band_members_band_company_feature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='band',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='musicas.company'),
            preserve_default=False,
        ),
    ]
