# Generated by Django 5.2.6 on 2025-09-10 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicas', '0006_alter_band_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='audio_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='song',
            name='chord_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='song',
            name='lyrics_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
